### ISSUE TITLE
Step does not work in some cases

### ISSUE THREAD

**Issue by f3mahmud** [fileformat/bitrise-step-appcenter-app-release#15]
Hi, thanks for creating the step.

While it works for certain apps and usually uploads for all apps. Something goes wrong when distributing.

This is the response I get: 

[00;31mAPI call failed with 400: <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>SyntaxError: Unexpected token <br> in JSON at position 69<br> &nbsp; &nbsp;at JSON.parse (&lt;anonymous&gt;)<br> &nbsp; &nbsp;at parse (/home/node/data/node_modules/body-parser/lib/types/json.js:89:19)<br> &nbsp; &nbsp;at /home/node/data/node_modules/body-parser/lib/read.js:121:18<br> &nbsp; &nbsp;at invokeCallback (/home/node/data/node_modules/raw-body/index.js:224:16)<br> &nbsp; &nbsp;at done (/home/node/data/node_modules/raw-body/index.js:213:7)<br> &nbsp; &nbsp;at IncomingMessage.onEnd (/home/node/data/node_modules/raw-body/index.js:273:7)<br> &nbsp; &nbsp;at IncomingMessage.emit (events.js:203:15)<br> &nbsp; &nbsp;at IncomingMessage.EventEmitter.emit (domain.js:448:20)<br> &nbsp; &nbsp;at endReadableNT (_stream_readable.js:1143:12)<br> &nbsp; &nbsp;at process._tickCallback (internal/process/next_tick.js:63:19)</pre>
</body>
</html>

I was wondering if you could look into this. This does work for certain apps at the same time though. So I am assuming the fix might be trivial, but slightly hard to find. Thanks!

**Comment by f3mahmud** [comment]
I realized the problem is with the release notes, The only istance it isnt a problem is where its a word or 2. Still trying to figure out what exactly causes the issue. Would be great if you could take a look at it, especially if it could accept environment vars

**Comment by f3mahmud** [comment]
Update: It seems as if it's just line breaks that are not allowed in the field. Is there any way to fix it such that it can accept line breaks?

**Comment by andrewtremblay-pear** [comment]
Confirmed, newline breaks the release_notes param due to unsanitized strings https://github.com/fileformat/bitrise-step-appcenter-app-release/blob/master/step.sh#L170 

Using jq to build the JSON rather than manually building it should fix this problem.

**Comment by jhass** [comment]
@fileformat Any plans on merging the proposed fix or doing on your own? :)

**Comment by andrewtremblay** [comment]
Looks like 1.0.4 encodes user input, including my release_notes fix. 
https://github.com/fileformat/bitrise-step-appcenter-app-release/commit/53de7d586a5118ba8931c7d72f87fdfd059ec627

I think this Issue can be closed.

**Comment by amarcuse** [comment]
Agreed.  I was waiting to close it until 1.0.4 (now 1.0.5) was accepted by bitrise

**Comment by fileformat** [comment]
Agreed.  I was waiting until 1.0.4 (now 1.0.5) was accepted by bitrise.

**Comment by cotispear** [comment]
Looks like the 1.0.5 release has been merged! 🎉

https://github.com/bitrise-io/bitrise-steplib/pull/2275
